// Shared Types

/** A synthetic user record with age and location attributes. */
export interface UserRecord {
  id: number;
  age: number;        // 18–80
  location: string;   // ISO code: 'SE', 'US', 'DE', etc.
}

/** Identifies which verification system is being benchmarked. */
export type SystemType = 'A_RAW' | 'B_PRED' | 'C_ZKP';

/** A single benchmark measurement row. */
export interface BenchmarkResult {
  system: SystemType;
  sample_size: number;
  user_id: number;
  latency_ns: bigint;
  cpu_time_ms: number;
  payload_bytes: number;
  verified: boolean;
  predicate_result: boolean;
  timestamp: Date;
}

/** The predicate under test: age >= threshold AND location === target. */
export interface PredicateConfig {
  ageThreshold: number;     // default: 18
  targetLocation: string;   // default: 'SE'
}

/** Default predicate for all benchmarks. */
export const DEFAULT_PREDICATE: PredicateConfig = {
  ageThreshold: 18,
  targetLocation: 'SE',
};

// System A types

/** Raw JSON payload sent by the Seller in System A. */
export interface RawPayload {
  age: number;
  location: string;
}

/** Verification result returned by the Buyer. */
export interface VerificationResult {
  verified: boolean;
  result: boolean;
}

// System B types (Predicate-Based)

/** A node in the OBDD. */
export interface OBDDNode {
  id: number;
  level: number;           // which bit this node checks
  lowChild: number;        // node id for bit=0
  highChild: number;       // node id for bit=1
  isTerminal: boolean;
  terminalValue?: boolean; // only for terminal nodes
}

/** Keys generated by the Notary for each OBDD level. */
export interface LevelKeys {
  L: Buffer;   // key for low (bit=0)
  R: Buffer;   // key for high (bit=1)
}

/** The Notary's commitment (setup output). */
export interface PredicateCommitment {
  rootHash: Buffer;
  levelKeys: LevelKeys[];
  nodeHashes: Map<number, Buffer>;
  auxValues: Map<number, Buffer>;
  obdd: OBDDNode[];
}

/** Witness generated by the Seller for a specific input. */
export interface PredicateWitness {
  result: boolean;
  pathAux: Buffer[];           // Aux values along the path (root → leaf)
  pathKeys: Buffer[];          // Chosen key (L_i or R_i) per level
  pathBits: number[];          // The input bits that determined the path
  leafHash: Buffer;            // Hash of the terminal value
}

// System C types (ZK)

/** Artifacts produced by the trusted setup (Notary). */
export interface ZKSetupArtifacts {
  wasmFile: string;       // path to compiled circuit WASM
  zkeyFile: string;       // path to proving key
  vkeyJson: object;       // verification key as JSON
}

/** Proof generated by the Seller. */
export interface ZKProof {
  proof: object;
  publicSignals: string[];
}

/** Encoding helper: convert ISO location code to integer. */
export function locationToInt(loc: string): number {
  let val = 0;
  for (let i = 0; i < loc.length; i++) {
    val = val * 256 + loc.charCodeAt(i);
  }
  return val;
}

/** Decode integer back to location string. */
export function intToLocation(val: number): string {
  const chars: string[] = [];
  while (val > 0) {
    chars.unshift(String.fromCharCode(val % 256));
    val = Math.floor(val / 256);
  }
  return chars.join('');
}
